JWT_ALG: "HS256"
JWT_SECRET_KEY: "973EC55AB463B504D25C835531F8758ED82BD1192FA17EBE444524145775883F"

AWS_ACCESS_KEY_ID: "AKIAYN3Q7W7J2GTX64AY"
AWS_SECRET_ACCESS_KEY: "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"
S3_BUCKET_NAME: "capsuleclosetimages"
REGION: "us-west-2"
AWS_ENDPOINT: "http:aws:s3:us-west-2:579520673747:accesspoint/itemimage"